probes = [
        # RouteViews
        'route-views2',
        'route-views3',
        'route-views4',
        'route-views5',
        'route-views6',
        'route-views7',
        'route-views8',

        'cix.atl',
        'route-views.ny',
        'route-views.chicago',
        'route-views.eqix',
        'route-views.isc',
        'route-views.flix',
        'route-views.mwix',
        'route-views.nwax',
        'route-views.sfmix',
        'route-views.telxatl',
        'pacwave.lax',

        'route-views.rio',
        'route-views.chile',
        'route-views.peru',
        'route-views2.saopaulo',
        'route-views.fortaleza',
        'pit.scl',
        'pitmx.qro',

        'amsix.ams',
        'route-views.amsix',
        'route-views.linx',
        'route-views.soxrs',
        'interlan.otp',
        'namex.fco',
        'decix.fra',
        'locix.fra',
        'route-views.gorex',

        'route-views.napafrica',
        'decix.jhb',
        'ixpn.los',

        'route-views.uaeix',
        'iraq-ixp.bgw',

        'route-views.sg',
        'route-views.wide',
        'route-views.phoix',
        'route-views.kixp',
        'route-views.jinx',
        'route-views.bdix',
        'route-views.bknix',
        'hkix.hkg',
        'kinx.icn',
        'iix.cgk',
        'getafix.mnl',

        'crix.sjo',
        'gixa',

        # RIPE RIS
        'rrc00',
        'rrc01',
        'rrc03',
        'rrc04',
        'rrc05',
        'rrc06',
        'rrc07',
        'rrc10',
        'rrc11',
        'rrc12',
        'rrc13',
        'rrc14',
        'rrc15',
        'rrc16',
        'rrc18',
        'rrc19',
        'rrc20',
        'rrc21',
        'rrc22',
        'rrc23',
        'rrc24',
        'rrc25',
        'rrc26',
    ]
